name: Build and DAST

#:[.'.]:>-------------------------------------
#:[.'.]:> Evento que dispara el workflow
#:[.'.]:> Se ejecuta en cada push a las ramas master y non-existent-branch
#:[.'.]:>-------------------------------------
on:
  push:
    branches: [ non-existent-branch, master ]

jobs:
  build:
    name: Build and DAST
    runs-on: ubuntu-latest

    steps:
      #:[.'.]:>-------------------------------------
      #:[.'.]:> Clona el repositorio
      #:[.'.]:>-------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      #:[.'.]:>-------------------------------------
      #:[.'.]:> Inicia un contenedor de PostgreSQL
      #:[.'.]:>-------------------------------------
      - name: Start PostgreSQL container
        run: |
          docker run -d \
            --name markitos-common-postgres \
            -e POSTGRES_USER=admin \
            -e POSTGRES_PASSWORD=admin \
            -e POSTGRES_DB=markitos-svc-boilerplates \
            -p 5432:5432 \
            postgres:16

      #:[.'.]:>-------------------------------------
      #:[.'.]:> Espera a que PostgreSQL esté listo
      #:[.'.]:>-------------------------------------
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if docker exec markitos-common-postgres pg_isready -U admin > /dev/null 2>&1; then
              echo "PostgreSQL is ready!"
              exit 0
            fi
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
          echo "PostgreSQL did not become ready in time."
          exit 1

      #:[.'.]:>-------------------------------------
      #:[.'.]:> Construye la imagen Docker
      #:[.'.]:>-------------------------------------
      - name: Build Docker image
        run: |
          docker build -t markitos-svc-boilerplates:${{ github.sha }} .
        env:
          VERSION: ${{ github.sha }}

      #:[.'.]:>-------------------------------------
      #:[.'.]:> Ejecuta la imagen Docker en segundo plano
      #:[.'.]:>-------------------------------------
      - name: Run Docker image
        run: |
          docker run -d \
            --name markitos-svc-boilerplates \
            --link markitos-common-postgres:markitos-common-postgres \
            -e DATABASE_DSN="host=markitos-common-postgres user=admin password=admin dbname=markitos-svc-boilerplates sslmode=disable" \
            -e HTTP_SERVER_ADDRESS=":3000" \
            -e GRPC_SERVER_ADDRESS=":30000" \
            -p 3000:3000 \
            -p 30000:30000 \
            markitos-svc-boilerplates:${{ github.sha }}

      #:[.'.]:>-------------------------------------
      #:[.'.]:> Espera a que la aplicación esté lista
      #:[.'.]:>-------------------------------------
      - name: Wait for application to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Application is ready!"
              exit 0
            fi
            echo "Waiting for application to be ready..."
            sleep 2
          done
          echo "Application did not become ready in time."
          exit 1

      #:[.'.]:>-------------------------------------
      #:[.'.]:> Ejecuta análisis DAST con ZAP y muestra el reporte
      #:[.'.]:>-------------------------------------
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          format: 'text'
          failOnWarnings: false
          failOnError: false
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd_options: '-d'
      #:[.'.]:>-------------------------------------
      #:[.'.]:> Limpia los contenedores al finalizar
      #:[.'.]:>-------------------------------------
      - name: Cleanup
        if: always()
        run: |
          docker stop markitos-svc-boilerplates || true
          docker rm markitos-svc-boilerplates || true
          docker stop markitos-common-postgres || true
          docker rm markitos-common-postgres || true